services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  B13\AuthorizedPreview\:
    resource: '../Classes/*'

  B13\AuthorizedPreview\Controller\PreviewController:
    tags: ['backend.controller']
